# Generated by Django 3.0.8 on 2020-07-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
