# Generated by Django 3.0.8 on 2020-07-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManager', '0002_photos_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
