# Generated by Django 3.0.8 on 2020-07-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManager', '0006_myphotos_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='myphotos',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
